/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIS;

import javax.swing.JOptionPane;

/**
 *
 * @author nguyenphong
 */
public class frmStaff extends javax.swing.JFrame {

    /**
     * Creates new form frmStaff
     */
    public static String usr, pwd, role;
    private frmChangePassword pass;

    public frmStaff() {
        initComponents();
        this.setTitle("Tài khoản: " + usr + "\tMật khẩu: " + pwd + "\tChức vụ: " + role);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelStaff = new javax.swing.JDesktopPane();
        menuStaff = new javax.swing.JMenuBar();
        mnHome = new javax.swing.JMenu();
        itemChangepass = new javax.swing.JMenuItem();
        itemLogout = new javax.swing.JMenuItem();
        mnFeature = new javax.swing.JMenu();
        itemCustomer = new javax.swing.JMenuItem();
        itemCard = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                ClosingForm(evt);
            }
        });

        javax.swing.GroupLayout panelStaffLayout = new javax.swing.GroupLayout(panelStaff);
        panelStaff.setLayout(panelStaffLayout);
        panelStaffLayout.setHorizontalGroup(
            panelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1288, Short.MAX_VALUE)
        );
        panelStaffLayout.setVerticalGroup(
            panelStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
        );

        mnHome.setIcon(new javax.swing.ImageIcon("/Users/phongnguyen/Desktop/JAVA/Projects/img/icon/home.png")); // NOI18N
        mnHome.setText("Trang chủ");

        itemChangepass.setIcon(new javax.swing.ImageIcon("/Users/phongnguyen/Desktop/JAVA/Projects/img/icon/changepass.png")); // NOI18N
        itemChangepass.setText("Đổi mật khẩu");
        itemChangepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePassword(evt);
            }
        });
        mnHome.add(itemChangepass);

        itemLogout.setIcon(new javax.swing.ImageIcon("/Users/phongnguyen/Desktop/JAVA/Projects/img/icon/logout.png")); // NOI18N
        itemLogout.setText("Đăng xuất");
        itemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout(evt);
            }
        });
        mnHome.add(itemLogout);

        menuStaff.add(mnHome);

        mnFeature.setIcon(new javax.swing.ImageIcon("/Users/phongnguyen/Desktop/JAVA/Projects/img/icon/catalog.png")); // NOI18N
        mnFeature.setText("Danh mục");
        mnFeature.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        itemCustomer.setIcon(new javax.swing.ImageIcon("/Users/phongnguyen/Desktop/JAVA/Projects/img/icon/customer.png")); // NOI18N
        itemCustomer.setText("Quản lý khách hàng");
        mnFeature.add(itemCustomer);

        itemCard.setIcon(new javax.swing.ImageIcon("/Users/phongnguyen/Desktop/JAVA/Projects/img/icon/card.png")); // NOI18N
        itemCard.setText("Quản lý thẻ");
        mnFeature.add(itemCard);

        menuStaff.add(mnFeature);

        setJMenuBar(menuStaff);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelStaff)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelStaff)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ChangePassword(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePassword
        if (pass == null || pass.isClosed()) {
            pass = new frmChangePassword();
            pass.setLocation(this.getWidth() / 2 - pass.getWidth() / 2, (this.getHeight() - 20) / 2 - pass.getHeight() / 2 - 20);
            panelStaff.add(pass);
            pass.setVisible(true);
        } else {
            pass.setLocation(this.getWidth() / 2 - pass.getWidth() / 2, (this.getHeight() - 20) / 2 - pass.getHeight() / 2 - 20);
            pass.setVisible(true);
        }
    }//GEN-LAST:event_ChangePassword

    private void ClosingForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_ClosingForm
        if (JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát ứng dụng?", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) != JOptionPane.YES_OPTION) {
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        } else {
            usr = pwd = role = null;
            this.setTitle(null);
            this.dispose();
            new frmHome().setVisible(true);
        }
    }//GEN-LAST:event_ClosingForm

    private void Logout(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout
        if (JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất?", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) != JOptionPane.YES_OPTION) {
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        } else {
            usr = pwd = role = null;
            this.setTitle(null);
            this.dispose();
            new frmHome().setVisible(true);
        }
    }//GEN-LAST:event_Logout

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmStaff().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemCard;
    private javax.swing.JMenuItem itemChangepass;
    private javax.swing.JMenuItem itemCustomer;
    private javax.swing.JMenuItem itemLogout;
    private javax.swing.JMenuBar menuStaff;
    private javax.swing.JMenu mnFeature;
    private javax.swing.JMenu mnHome;
    private javax.swing.JDesktopPane panelStaff;
    // End of variables declaration//GEN-END:variables
}
